/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rmutk.pskw;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;


/**
 *
 * @author admaun
 */

public class GrBoard extends javax.swing.JPanel {

    private class Tower extends Rectangle
    {
        public int HasDisk;
        
        public Tower(int x, int y)
        {
              this.setRect(x, y, 20, 240);
              HasDisk=0;
        }
        
    }
    
    private class Disk
    {
        public Color[] CD = {
                                    Color.BLACK,
                                    Color.LIGHT_GRAY,
                                    Color.MAGENTA,
                                    Color.BLUE,
                                    Color.CYAN,
                                    Color.GREEN,
                                    Color.YELLOW,
                                    Color.ORANGE,
                                    Color.RED,
                                    Color.pink
                            };
        
        private int DiskNo;
        private Color DiskColor;
        private Rectangle DiskShp;
        
        public Disk (int x, int y, int No) 
        {
            DiskShp = new Rectangle(x-(200-No*15)/2, y-20, 200-No*15, 20);
            DiskNo = No;
            DiskColor = CD[No];
        }

    }
    

    /**
     * Creates new form GrBoard
     */
    private Tower[] Twr = new Tower[3];
    private Disk[]  Dsk = new Disk[10];
    public int NOfDisk;
    
    public GrBoard(int NoDisk) {
        initComponents();
        NOfDisk = NoDisk;
        InitialBoard();
        
    }
    
    public void InitialBoard()
    {
/*        int i;
        for (i=0; i<10; i++)
        {
            Dsk[i].DiskShp.setLocation ((int) Twr[0].getCenterX()-(200-i*15)/2 , 
                               (int) (Twr[0].getY()+Twr[0].getHeight()-i*20)-20);
            
        }
        repaint();  
*/
        int i;

//        removeAll();
//       repaint();
        
        Twr[0] = new Tower(100, 20);
        Twr[1] = new Tower(350, 20);
        Twr[2] = new Tower(600, 20);
        
        Twr[0].HasDisk = NOfDisk;
        Twr[1].HasDisk = 0;
        Twr[2].HasDisk = 0;
        
    
        for (i=0; i<NOfDisk; i++)
        {
            Dsk[i] = new Disk( (int) Twr[0].getCenterX(), 
                               (int) (Twr[0].getY()+Twr[0].getHeight()-i*20),
                                i);
        }
        repaint();
    }
    
    public void MoveDisk(int i, int T1, int T2)
    {
        Dsk[i].DiskShp.setLocation(
                (int) Twr[T2].getCenterX()-(200-i*15)/2, 
                (int) (Twr[T2].getY()+Twr[T2].getHeight()-Twr[T2].HasDisk*20)-20);
        Twr[T1].HasDisk --;
        Twr[T2].HasDisk ++;
        
        repaint();
        
    }
   
     @Override
     public void paintComponent(Graphics g) 
     {
         super.paintComponent(g);
         Graphics2D g2 = (Graphics2D) g;
         int i;
         Color OldFillColor;
         
         g2.fill(Twr[0]);
         g2.fill(Twr[1]);
         g2.fill(Twr[2]);
         
         OldFillColor = g2.getColor();
         for (i=0; i<NOfDisk; i++)
         {

             g2.setColor(Dsk[i].DiskColor);
             g2.fill(Dsk[i].DiskShp);
             g2.setColor( new Color(Dsk[i].DiskColor.getRGB()^0xFFFFFF));
             g2.drawString( String.format("Disk %d", i),  
                     (int) Dsk[i].DiskShp.getCenterX()-20,                            
                     (int) Dsk[i].DiskShp.getCenterY()+4 );
             
               
         }
         
     }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
